"""Add risks field to ComparisonResult

Revision ID: 79bf5565acfc
Revises: 
Create Date: 2024-11-19 06:42:09.078720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79bf5565acfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comparison_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comparison_result', schema=None) as batch_op:
        batch_op.drop_column('risks')

    # ### end Alembic commands ###
